apiVersion : apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo \"$(date +'%T %F')\" >> /logs/app.log ; sleep 5; done"]
          volumeMounts:
          - mountPath: /logs
            name: log-volume
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
          - mountPath: /logs
            name: log-volume
          env:
            - name: HTTP_PORT
              value: "8080"
      volumes:
      - name: log-volume
        emptyDir:
          sizeLimit: 500Mi