---
- name: Prepare env
  hosts: kuber
  remote_user: ubuntu
  gather_facts: false
  become: true
  tasks:
    - name: Apt update
      apt:
        update_cache: true
        force_apt_get: yes
    - name: Apt upgrade
      apt:
        upgrade: yes
        force_apt_get: yes
    - name: Install snapd
      apt:
        name: snapd
        update_cache: true
    - name: Install microk8s
      shell: snap install microk8s --classic
    - name: usermod microk8s
      shell: usermod -a -G microk8s ubuntu
    - name: Change ownership of .kube directory to user 'ubuntu'
      file:
        path: "{{ lookup('env', 'HOME') + '/.kube' }}"
        owner: ubuntu
        group: ubuntu
        recurse: yes
        
# newgrp microk8s
# microk8s status --wait-ready
# microk8s enable dashboard
# microk8s enable ingress
# nano /var/snap/microk8s/current/certs/csr.conf.template
# sudo microk8s refresh-certs --cert front-proxy-client.crt
# microk8s config

