apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
      initContainers:
        - name: init-nginx-service
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup nginx-svc; do echo waiting for nginx-svc; sleep 2; done;']