{
 "title": "Homework",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[1m]))"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[1m]))"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[1m]))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|udev\", mountpoint=\"/\"}"
    }
   ]
  }
 ]
}