---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: admin
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  remote_user: admin
  roles:
    - vector

- name: Install Lighthouse
  hosts: lighthouse
  remote_user: admin
  roles:
    - lighthouse
