apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nfs
  labels:
    app: deployment-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-nfs
  template:
    metadata:
      labels:
        app: deployment-nfs
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
        volumeMounts:
        - name: volume-nfs
          mountPath: /input
      volumes:
      - name: volume-nfs
        persistentVolumeClaim:
          claimName: pvc-nfs